[versions]
mobileLibraryVersion = "1.0.0"

activityCompose = "1.12.4"
androidxTestRunner = "1.7.0"
agp = "8.13.2"
composeBom = "2026.02.00"
coreKtx = "1.17.0"
hilt = "2.57.2"
junit = "4.13.2"
junitVersion = "1.3.0"
junit5 = "5.14.0"
mockk = "1.14.9"
kotlin = "2.2.21"
kotlinxCoroutines = "1.10.2"
ksp = "2.3.0"
ktlint = "14.0.1"
lifecycleRuntimeKtx = "2.10.0"
mockwebserver = "5.3.2"
robolectric = "4.16.1"
truth = "1.4.5"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-core = { group = "com.google.dagger", name = "hilt-core", version.ref = "hilt" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-vintage-engine = { group = "org.junit.vintage", name = "junit-vintage-engine", version.ref = "junit5" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "mockwebserver" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
test-junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
test-junit5-api = { group = "org.junit.jupiter", name = "junit-jupiter-api" }
test-junit5-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit5" }
test-junit5-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine" }
test-junit5-params = { group = "org.junit.jupiter", name = "junit-jupiter-params" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }

android-gradleApiPlugin = { group = "com.android.tools.build", name = "gradle-api", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }

ioffeivan-android-application = { id = "ioffeivan.android.application" }
ioffeivan-android-library = { id = "ioffeivan.android.library" }
ioffeivan-compose = { id = "ioffeivan.compose" }
ioffeivan-hilt = { id = "ioffeivan.hilt" }
ioffeivan-jvm-library = { id = "ioffeivan.jvm.library" }
