name: Build

on:
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  check-build-logic-and-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
          cache-read-only: false

      - name: Check Convention Plugins
        run: ./gradlew :build-logic:plugins:check

      - name: Run ktlint
        run: ./gradlew ktlintCheck

      - name: Upload ktlint report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: ktlint.html
          path: '**/build/reports/ktlint/'
          retention-days: 7
  unit-test:
    needs: [ check-build-logic-and-lint ]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
          cache-read-only: false

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Upload test report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: unit_test_report
          path: '**/build/reports/tests/testDebugUnitTest/'
          retention-days: 7

    instrumentation-test:
      needs: [ unit-test ]
      runs-on: ubuntu-latest
      timeout-minutes: 30
      steps:
        - name: Enable KVM group perms
          run: |
            echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
            sudo udevadm control --reload-rules
            sudo udevadm trigger --name-match=kvm
            ls /dev/kvm

        - name: Checkout the code
          uses: actions/checkout@v4

        - name: Setup Java
          uses: actions/setup-java@v4
          with:
            distribution: 'zulu'
            java-version: 17

        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@v4
          with:
            gradle-version: wrapper
            cache-read-only: false

        - name: Run instrumentation tests
          uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: 29
            script: ./gradlew connectedDebugAndroidTest

        - name: Upload test report
          if: ${{ failure() }}
          uses: actions/upload-artifact@v4
          with:
            name: instrumentation_test_report
            path: '**/build/reports/androidTests/connected/'
            retention-days: 7